
name: idiyaflow
description: A mind map Flutter app per specs
version: 0.1.0+1
environment:
  sdk: ">=2.17.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  pdf: ^3.8.1
  file_picker: ^5.2.5
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
